winguhub/avatar/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('winguhub.avatar.views',
    url('^add/$', 'add', name='avatar_add'),
    url('^group/(?P<gid>\d+)/add/$', 'group_add', name='avatar_group_add'),
#    url('^change/$', 'change', name='avatar_change'),
#    url('^delete/$', 'delete', name='avatar_delete'),
    url('^render_primary/(?P<user>[^/]+)/(?P<size>[\d]+)/$', 'render_primary', name='avatar_render_primary'),    
)

winguhub/group/urls.py
from django.conf.urls.defaults import *

from views import group_info, group_members, group_member_operations, group_add_admin, \
    group_manage, msg_reply, msg_reply_new, group_recommend, \
    create_group_repo, group_joinrequest, attention, group_message_remove, \
    group_remove_admin, group_discuss, group_wiki, group_wiki_create, \
    group_wiki_page_new, group_wiki_page_edit, group_wiki_pages, \
    group_wiki_page_delete, group_remove, group_dismiss, group_quit, \
    group_make_public, group_revoke_public

urlpatterns = patterns('',
    url(r'^(?P<group_id>\d+)/$', group_info, name='group_info'),
    url(r'^(?P<group_id>\d+)/discuss/$', group_discuss, name='group_discuss'),
    url(r'^(?P<group_id>\d+)/wiki/$', group_wiki, name='group_wiki'),
    url(r'^(?P<group_id>\d+)/wiki/(?P<page_name>[^/]+)/$', group_wiki, name='group_wiki'),
    url(r'^(?P<group_id>\d+)/wiki_pages/$', group_wiki_pages, name='group_wiki_pages'),
    url(r'^(?P<group_id>\d+)/wiki_create/$', group_wiki_create, name='group_wiki_create'),
    url(r'^(?P<group_id>\d+)/wiki_page_new/$', group_wiki_page_new, name='group_wiki_page_new'),
    url(r'^(?P<group_id>\d+)/wiki_page_edit/(?P<page_name>[^/]+)$', group_wiki_page_edit, name='group_wiki_page_edit'),
    url(r'^(?P<group_id>\d+)/wiki_page_delete/(?P<page_name>[^/]+)$', group_wiki_page_delete, name='group_wiki_page_delete'),
    url(r'^reply/(?P<msg_id>[\d]+)/$', msg_reply, name='msg_reply'),
    url(r'^reply/new/$', msg_reply_new, name='msg_reply_new'),
    url(r'^(?P<group_id>\d+)/manage/$', group_manage, name='group_manage'),
    url(r'^(?P<group_id>\d+)/remove/$', group_remove, name='group_remove'),
    url(r'^(?P<group_id>\d+)/dismiss/$', group_dismiss, name='group_dismiss'),
    url(r'^(?P<group_id>\d+)/make_pub/$', group_make_public, name='group_make_pub'),
    url(r'^(?P<group_id>\d+)/revoke_pub/$', group_revoke_public, name='group_revoke_pub'),
    url(r'^(?P<group_id>\d+)/quit/$', group_quit, name='group_quit'),
    url(r'^(?P<group_id>[\d]+)/create-repo/$', create_group_repo, name='create_group_repo'),
    url(r'^(?P<group_id>[\d]+)/members/$', group_members, name='group_members'),
    (r'^(?P<group_id>[\d]+)/member/(?P<user_name>[^/]+)/$', group_member_operations),
    url(r'^(?P<group_id>\d+)/msgdel/(?P<msg_id>\d+)/$', group_message_remove, name='group_message_remove'),
    url(r'^(?P<group_id>\d+)/admin/add/$', group_add_admin, name='group_add_admin'),
    url(r'^(?P<group_id>\d+)/admin/remove/$', group_remove_admin, name='group_remove_admin'),
    url(r'^recommend/$', group_recommend, name='group_recommend'),
    url(r'^attention/$', attention, name='group_attention'),
    url(r'^joinrequest/(?P<group_id>[\d]+)/$', group_joinrequest, name='group_joinrequest'),
)

import winguhub.settings as settings

if settings.ENABLE_PUBFILE:
    from winguhub_extra.pubfile.views import group_pubfiles, group_pubfile_add, group_pubfile_delete, group_pubfile_edit, group_pubfile_download

    urlpatterns += patterns('',
        url(r'^(?P<group_id>\d+)/files/$', group_pubfiles, name='group_pubfiles'),
        url(r'^(?P<group_id>\d+)/file/add/$', group_pubfile_add, name='group_pubfile_add'),
        url(r'^(?P<group_id>\d+)/file/(?P<file_id>\d+)/delete/$', group_pubfile_delete, name='group_pubfile_delete'),
        url(r'^(?P<group_id>\d+)/file/(?P<file_id>\d+)/edit/$', group_pubfile_edit, name='group_pubfile_edit'),
        url(r'^(?P<group_id>\d+)/file/d/(?P<file_name>.+)$', group_pubfile_download, name='group_pubfile_download'),
    )

winguhub/share/urls.py
from django.conf.urls.defaults import *

from views import *

urlpatterns = patterns('',
    url(r'^$', list_share_out_repos, name='share_admin'),
    url(r'^links/$', list_shared_links, name='list_shared_links'),
    url(r'^files/$', list_priv_shared_files, name='list_priv_shared_files'),
                       
    url(r'^add/$', share_repo, name='share_repo'),
    url(r'^remove/$', repo_remove_share, name='repo_remove_share'),

    url(r'^link/get/$', get_shared_link, name='get_shared_link'),
    url(r'^link/remove/$', remove_shared_link, name='remove_shared_link'),
    url(r'^link/send/$', send_shared_link, name='send_shared_link'),
    url(r'^link/save/$', save_shared_link, name='save_shared_link'),

    url(r'^permission_admin/$', share_permission_admin, name='share_permission_admin'),


    # url('^remove/(?P<token>[^/]{24,24})/$', remove_anonymous_share, name='remove_anonymous_share'),
    # url('^(?P<token>[^/]{24})/$', anonymous_share_confirm, name='anonymous_share_confirm'),
                       
)

winguhub/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
# from django.views.generic.simple import direct_to_template

from winguhub.views import *
from winguhub.views.file import view_file, view_history_file, view_trash_file,\
    view_snapshot_file, file_edit, view_shared_file, view_file_via_shared_dir,\
    text_diff, view_priv_shared_file
from winguhub.views.repo import repo, repo_history_view
from notifications.views import notification_list
from group.views import group_list
from message.views import user_msg_list
from share.views import user_share_list, gen_private_file_share, \
    rm_private_file_share, save_private_file_share
from winguhub.views.wiki import personal_wiki, personal_wiki_pages, \
    personal_wiki_create, personal_wiki_page_new, personal_wiki_page_edit, \
    personal_wiki_page_delete
from winguhub.views.sysadmin import sys_repo_admin, sys_user_admin, \
    sys_group_admin, user_info, user_add, user_remove, user_make_admin, \
    user_remove_admin, user_reset, user_activate, sys_publink_admin
from winguhub.views.ajax import *

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^winguhub/', include('winguhub.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #(r'^admin/', include(admin.site.urls)),

    (r'^accounts/', include('winguhub.base.registration_urls')),

    (r'^$', root),
    #url(r'^home/$', direct_to_template, { 'template': 'home.html' } ),
    url(r'^home/my/$', myhome, name='myhome'),
    url(r'^home/wiki/$', personal_wiki, name='personal_wiki'),
    url(r'^home/wiki/(?P<page_name>[^/]+)/$', personal_wiki, name='personal_wiki'),
    url(r'^home/wiki_pages/$', personal_wiki_pages, name='personal_wiki_pages'),
    url(r'^home/wiki_create/$', personal_wiki_create, name='personal_wiki_create'),
    url(r'^home/wiki_page_new/$', personal_wiki_page_new, name='personal_wiki_page_new'),
    url(r'^home/wiki_page_edit/(?P<page_name>[^/]+)$', personal_wiki_page_edit, name='personal_wiki_page_edit'),
    url(r'^home/wiki_page_delete/(?P<page_name>[^/]+)$', personal_wiki_page_delete, name='personal_wiki_page_delete'),

    url(r'^home/clients/$', client_mgmt, name='client_mgmt'),
    url(r'^home/clients/unsync/$', client_unsync, name='client_unsync'),

    # url(r'^home/public/reply/(?P<msg_id>[\d]+)/$', innerpub_msg_reply, name='innerpub_msg_reply'),
    # url(r'^home/owner/(?P<owner_name>[^/]+)/$', ownerhome, name='ownerhome'),

    (r'^repo/create/$', repo_create),
    (r'^repo/upload_check/$', validate_filename),
    url(r'^repo/unsetinnerpub/(?P<repo_id>[-0-9a-f]{36})/$', unsetinnerpub, name='unsetinnerpub'),
    url(r'^repo/set_password/$', repo_set_password, name="repo_set_password"),
    url(r'^repo/revert_file/(?P<repo_id>[-0-9a-f]{36})/$', repo_revert_file, name='repo_revert_file'),
    url(r'^repo/revert_dir/(?P<repo_id>[-0-9a-f]{36})/$', repo_revert_dir, name='repo_revert_dir'),
    url(r'^repo/download_dir/(?P<repo_id>[-0-9a-f]{36})/$', repo_download_dir, name='repo_download_dir'),
    (r'^repo/upload_error/(?P<repo_id>[-0-9a-f]{36})/$', upload_file_error),
    (r'^repo/update_error/(?P<repo_id>[-0-9a-f]{36})/$', update_file_error),
    url(r'^repo/file_revisions/(?P<repo_id>[-0-9a-f]{36})/$', file_revisions, name='file_revisions'),
    url(r'^repo/text_diff/(?P<repo_id>[-0-9a-f]{36})/$', text_diff, name='text_diff'),
    url(r'^repo/(?P<repo_id>[-0-9a-f]{36})/$', repo, name='repo'),
    url(r'^repo/history/(?P<repo_id>[-0-9a-f]{36})/$', repo_history, name='repo_history'),
    (r'^repo/history/revert/(?P<repo_id>[-0-9a-f]{36})/$', repo_history_revert),
    url(r'^repo/history/view/(?P<repo_id>[-0-9a-f]{36})/$', repo_history_view, name='repo_history_view'),
    url(r'^repo/recycle/(?P<repo_id>[-0-9a-f]{36})/$', repo_recycle_view, name='repo_recycle_view'),
    url(r'^repo/snapshot/view/(?P<repo_id>[-0-9a-f]{36})/$', repo_view_snapshot, name='repo_view_snapshot'),
    url(r'^repo/history/changes/(?P<repo_id>[-0-9a-f]{36})/$', repo_history_changes, name='repo_history_changes'),
    (r'^repo/remove/(?P<repo_id>[-0-9a-f]{36})/$', repo_remove),
    url(r'^repo/(?P<repo_id>[-0-9a-f]{36})/files/$', view_file, name="repo_view_file"),
    url(r'^repo/(?P<repo_id>[-0-9a-f]{36})/history/files/$', view_history_file, name="view_history_file"),
    url(r'^repo/(?P<repo_id>[-0-9a-f]{36})/trash/files/$', view_trash_file, name="view_trash_file"),
    url(r'^repo/(?P<repo_id>[-0-9a-f]{36})/snapshot/files/$', view_snapshot_file, name="view_snapshot_file"),
    url(r'^repo/(?P<repo_id>[-0-9a-f]{36})/file/edit/$', file_edit, name='file_edit'),
    url(r'^repo/(?P<repo_id>[-0-9a-f]{36})/privshare/$', gen_private_file_share, name='gen_private_file_share'),
    url(r'^repo/(?P<repo_id>[-0-9a-f]{36})/(?P<obj_id>[0-9a-f]{40})/$', repo_access_file, name='repo_access_file'),
    (r'^repo/save_settings$', repo_save_settings),

    ### share file/dir ###
    url(r'^s/f/(?P<token>[a-f0-9]{10})/$', view_priv_shared_file, name="view_priv_shared_file"),
    url(r'^s/f/(?P<token>[a-f0-9]{10})/rm/$', rm_private_file_share, name="rm_private_file_share"),
    url(r'^s/f/(?P<token>[a-f0-9]{10})/save/$', save_private_file_share, name='save_private_file_share'),
    url(r'^f/(?P<token>[a-f0-9]{10})/$', view_shared_file, name='view_shared_file'),
    url(r'^d/(?P<token>[a-f0-9]{10})/$', view_shared_dir, name='view_shared_dir'),
    url(r'^d/(?P<token>[a-f0-9]{10})/files/$', view_file_via_shared_dir, name='view_file_via_shared_dir'),

    ### Misc ###
    (r'^file_upload_progress_page/$', file_upload_progress_page),
    (r'^events/$', events),
    (r'^pdf_full_view/$', pdf_full_view),
    url(r'^i18n/$', i18n, name='i18n'),
    (r'^download/repo/$', repo_download),                       
    (r'^wingufile_access_check/$', wingufile_access_check),
    url(r'^convert_cmmt_desc_link/$', convert_cmmt_desc_link, name='convert_cmmt_desc_link'),
    url(r'^user/(?P<id_or_email>[^/]+)/msgs/$', user_msg_list, name='user_msg_list'),
    url(r'^user/(?P<id_or_email>[^/]+)/shares/$', user_share_list, name='user_share_list'),

    ### Ajax ###
    (r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/dirents/$', get_dirents),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/dirents/delete/$', delete_dirents, name='delete_dirents'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/dirents/move/$', mv_dirents, name='mv_dirents'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/dirents/copy/$', cp_dirents, name='cp_dirents'),
    url(r'^ajax/group/(?P<group_id>\d+)/repos/$', get_group_repos, name='get_group_repos'),
    url(r'^ajax/my-unenc-repos/$', get_my_unenc_repos, name='get_my_unenc_repos'),
    url(r'^ajax/contacts/$', get_contacts, name='get_contacts'),

    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/dir/$', list_dir, name='repo_dir_data'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/dir/more/$', list_dir_more, name='list_dir_more'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/dir/new/$', new_dir, name='new_dir'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/dir/rename/$', rename_dirent, name='rename_dir'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/dir/delete/$', delete_dirent, name='delete_dir'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/dir/mv/$', mv_dir, name='mv_dir'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/dir/cp/$', cp_dir, name='cp_dir'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/dir/check_sub_repo/$', check_sub_repo, name='check_sub_repo'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/dir/create_sub_repo/$', create_sub_repo, name='create_sub_repo'),

    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/file/new/$', new_file, name='new_file'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/file/rename/$', rename_dirent, name='rename_file'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/file/delete/$', delete_dirent, name='delete_file'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/file/mv/$', mv_file, name='mv_file'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/file/cp/$', cp_file, name='cp_file'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/file/star/$', repo_star_file, name='repo_star_file'),
    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/file/unstar/$', repo_unstar_file, name='repo_unstar_file'),

    url(r'^ajax/repo/(?P<repo_id>[-0-9a-f]{36})/current_commit/$', get_current_commit, name='get_current_commit'),

    ### Apps ###
    (r'^api2/', include('winguhub.api2.urls')),
    (r'^avatar/', include('winguhub.avatar.urls')),
    (r'^notification/', include('winguhub.notifications.urls')),
    (r'^contacts/', include('winguhub.contacts.urls')),                       
    (r'^group/', include('winguhub.group.urls')),
    url(r'^groups/', group_list, name='group_list'),
    (r'^message/', include('winguhub.message.urls')),     
    (r'^profile/', include('winguhub.profile.urls')),
    (r'^share/', include('winguhub.share.urls')),

    ### system admin ###                       
    (r'^sys/seafadmin/$', sys_repo_admin),
    url(r'^sys/useradmin/$', sys_user_admin, name='sys_useradmin'),
    url(r'^sys/groupadmin/$', sys_group_admin, name='sys_group_admin'),
    url(r'^sys/publinkadmin/$', sys_publink_admin, name='sys_publink_admin'),
    url(r'^sys/notificationadmin/', notification_list, name='notification_list'),
    url(r'^useradmin/add/$', user_add, name="user_add"),
    (r'^useradmin/remove/(?P<user_id>[^/]+)/$', user_remove),
    url(r'^useradmin/makeadmin/(?P<user_id>[^/]+)/$', user_make_admin, name='user_make_admin'),
    url(r'^useradmin/removeadmin/(?P<user_id>[^/]+)/$', user_remove_admin, name='user_remove_admin'),
    url(r'^useradmin/info/(?P<email>[^/]+)/$', user_info, name='user_info'),

winguhub/group/forms.py
# encoding: utf-8
import os

from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from seaserv import is_valid_filename

from winguhub.utils import validate_group_name

class MessageForm(forms.Form):
    message = forms.CharField(max_length=2048)

class MessageReplyForm(forms.Form):
    message = forms.CharField(max_length=2048)

class GroupRecommendForm(MessageForm):
    """
    A form used to recommend a file or directory.
    """
    repo_id = forms.CharField(max_length=40)
    path = forms.CharField()
    attach_type = forms.CharField(max_length=5)

class GroupAddForm(forms.Form):
    """
    A form used to add a new group.
    """
    group_name = forms.CharField(max_length=255, error_messages={
            'required': _(u'Group name can\'t be empty'),
            'max_length': _(u'Group name is too long (maximum is 255 characters)'),
            })
    def clean_group_name(self):
        group_name = self.cleaned_data['group_name']
        if not validate_group_name(group_name):
            error_msg = _(u'Group name can only contain letters, numbers or underline')
            raise forms.ValidationError(error_msg)
        else:
            return group_name

class GroupJoinMsgForm(forms.Form):
    """
    A form used to send group join request message.
    """
    group_join_msg = forms.CharField(max_length=255, error_messages={
            'required': _(u'Verification message can\'t be empty'),
            'max_length': _(u'Verification message is too long (maximun is 255 characters)'),
            })

class WikiCreateForm(forms.Form):
    """
    A form used to create wiki.
    """
    repo_name = forms.CharField(max_length=settings.MAX_FILE_NAME,
                                error_messages={
            'required': _(u'Name can\'t be empty'),
            'max_length': _(u'Name is too long (maximum is 255 characters)')
            })
    repo_desc = forms.CharField(max_length=100, error_messages={
            'required': _(u'Description can\'t be empty'),
            'max_length': _(u'Description is too long (maximum is 100 characters)')
            })

    def clean_repo_name(self):
        repo_name = self.cleaned_data['repo_name']
        if not is_valid_filename(repo_name):
            error_msg = _(u'"%s" is not a valid name') % repo_name
            raise forms.ValidationError(error_msg)
        else:
            return repo_name
    

winguhub/group/templates/group/add_member_email.html
{% load url from future %}{% load i18n %}{% autoescape off %}
{% blocktrans %}{{ email }} invite you to join group {{ group.group_name }}. Please go to the following page and sign up:{% endblocktrans %}
{{ protocol }}://{{ domain }}{% url 'registration_register' %}?src={{ to_email }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

winguhub/group/templates/group/group_join_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}{{ user }} want to join to Group "{{ group_name }}", here is the verification message: {% endblocktrans %}

{{ group_join_msg }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

winguhub/group/templates/group/group_members.html
{% extends base_template %}

{% load winguhub_tags avatar_tags group_avatar_tags i18n %}
{% load url from future %}

{% block sub_title %}{{group.group_name}} - {% endblock %}
{% block nav_group_class %}class="cur"{% endblock %}

{% block title_panel %}

<div class="tabnav">
    <div class="grp-profile fright">
        {% grp_avatar group.props.id 24 %}<span class="name">{{ group.group_name }}</span>
    </div>
    <ul class="tabnav-tabs">
        <li class="tabnav-tab"><a href="{% url 'group_info' group.id %}">{% trans "Libraries" %}</a></li>
        <li class="tabnav-tab"><a href="{% url 'group_discuss' group.id %}">{% trans "Discussion" %}</a></li>
        <li class="tabnav-tab"><a href="{% url 'group_wiki' group.id %}">{% trans "Wiki" %}</a></li>
        {% if enable_pubfile and group.is_pub %}
        <li class="tabnav-tab"><a href="{% url 'group_pubfiles' group.id %}">{% trans "Files" %}</a></li>
        {% endif %}
        <li class="tabnav-tab tabnav-tab-cur">{% trans "Members" %}</li>
        {% if is_staff %}
        <li class="tabnav-tab"><a href="{% url 'group_manage' group.id %}">{% trans "Admin" %}</a></li>
        {% endif %}
    </ul>
</div>

{% endblock %}

{% block left_panel %}
{% endblock %}

{% block right_panel %}
<ul class="user-list">
    {% for m in members %}
    {% with e=m.user_name id=m.user_name|id_or_email %}
    <li class="user ovhd">
    <a href="{% url 'user_msg_list' id %}" class="pic fleft">{% avatar e 48 %}</a>
    <div class="txt fright">
        <a class="name" href="{% url 'user_msg_list' id %}">{{ e|email2nickname }}</a>
        <p>{{ e }}</p>
        {% if m.can_be_contact %}
        <button class="add-to-contacts" data-email="{{ e }}">{% trans "Add to Contacts" %}</button>
        {% endif %}
    </div>
    </li>
    {% endwith %}
    {% endfor %}
</ul>

{% include 'snippets/add_to_contacts_form.html' %}

{% endblock %}

{% block extra_script %}
{% include 'snippets/add_to_contacts_js.html' %}

{% endblock %}

winguhub/group/templates/group/group_pubinfo.html
{% extends "myhome_base.html" %}
{% load winguhub_tags group_avatar_tags i18n %}
{% load url from future %}

{% block main_panel %}
<div class="user-profile narrow-panel ovhd">
  <div class="pic fleft">
    {% grp_avatar group.id 48 %}
    <button id="add">{% trans "Join Group" %}</button>
  </div>

  <div class="txt fright">
    <p>{% trans "Name: " %}{{ group.group_name }}</p>
    <p>{% trans "Creator: " %}{{ group.creator_name|email2nickname }}</p>
    <p>{% trans "Create at: " %}{{ group.timestamp|tsstr_sec }}</p>
    <p>{% trans "Members: " %}{{ members|length }}</p>
  </div>
</div>

<form id="group-join-form" class="hide" action="" method="post">{% csrf_token %}
  <label>{% trans "Verification Message" %}</label><br />
  <textarea id="id_group_join_msg" name="group_join_msg"></textarea><br />
  <p class="error hide"></p>
  <input type="submit" value="{% trans "Submit" %}" id="group-join-submit" />
</form>
{% endblock %}

{% block extra_script %}
<script type="text/javascript">
$('#add').click(function() {
    $('#group-join-form').modal({appendTo: '#main'});
});

$('#group-join-submit').click(function() {
    var self = $(this);
    self.attr('disabled', 'disabled');
    
    $.ajax({
        url: '{% url 'group_joinrequest' group.id %}',
        type: 'POST',
        dataType: 'json',
        cache: 'false',
        beforeSend: prepareCSRFToken,
        data: {
            'group_join_msg': $('#id_group_join_msg').val(),
        },
        success: function(data) {
            self.removeAttr('disabled');
            location.reload(true);
        },
        error: function(data, textStatus, jqXHR) {
            var errors = $.parseJSON(data.responseText);
            $.each(errors, function(index, value) {
                if (index == 'error') {
                    apply_form_error('group-join-form', value);
                } else {
                    apply_form_error('group-join-form', value[0]);
                }
            });
            self.removeAttr('disabled');
        }
    });

    return false;
});
</script>
{% endblock %}

winguhub/group/templates/group/group_reply_list.html
{% load winguhub_tags avatar_tags i18n %}
{% load url from future %}

{% for r in replies %}
{% with id=r.from_email|id_or_email name=r.from_email|email2nickname %}
<li class="reply w100 ovhd">
<a href="{% url 'user_msg_list' id %}" class="pic fleft">{% avatar r.from_email 28 %}</a>
<div class="txt">
    <a href="{% url 'user_msg_list' id %}">{{ name }}</a>
    <span class="time">{{ r.timestamp|translate_winguhub_time }}</span>
    <span class="reply-at op vh" data="{{ name }}">{% trans 'Reply' %}</span>
    <p class="reply-con">{{ r.message|winguhub_urlize|find_at }}</p>
</div>
</li>
{% endwith %}
{% endfor %}

winguhub/group/templates/group/groups.html
{% extends "myhome_base.html" %}
{% load winguhub_tags avatar_tags i18n %}
{% load url from future %}

{% block sub_title %}{% trans "Groups" %} - {% endblock %}
{% block nav_group_class %}class="cur"{% endblock %}

{% block left_panel %}
{% include "group/groups_left_panel.html" %}
{% endblock %}

{% block right_panel %}
{% include "group/groups_right_panel.html" %}
{% endblock %}

{% block extra_script %}
<script type="text/javascript">
{% url 'group_list' as group_add_url %}
{% with post_url=group_add_url %}
{% include "snippets/group_add_js.html" %}
{% endwith %}
</script>
{% endblock %}

winguhub/group/templates/group/groups_left_panel.html
{% load i18n %}
<div class="info-item">
    <h3 class="info-item-top">{% trans "Tips" %}</h3>
    <div class="info-item-bottom">
        <p class="not-last">{% trans "After creating a group, you can add members and share libraries into it." %}</p>
        {% if not cloud_mode %}
        <p>{% trans "You can also share libraries into groups that you're not in." %}</p>
        {% endif %}
    </div>
</div>